---
# tasks file for bootstrap-ansible-auth
- include: debian.yml
  when: ansible_os_family == "Debian"
# tasks file for bootstrap-ansible-auth
- include: yum.yml
  when: ansible_os_family == "RedHat"
